# Generated by Django 4.1.3 on 2022-11-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=200)),
                ("lastname", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("birth_date", models.DateField()),
                ("contact", models.CharField(blank=True, max_length=100)),
            ],
            options={"db_table": "web_member",},
        ),
        migrations.RemoveField(model_name="book", name="author",),
        migrations.RemoveField(model_name="book", name="categories",),
        migrations.DeleteModel(name="Author",),
        migrations.DeleteModel(name="Book",),
        migrations.DeleteModel(name="Category",),
    ]
